// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: pkg/errors/grpc/error.proto

package grpc

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type InvalidArgument struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Ditales       []*Ditale              `protobuf:"bytes,10,rep,name=Ditales,proto3" json:"Ditales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InvalidArgument) Reset() {
	*x = InvalidArgument{}
	mi := &file_pkg_errors_grpc_error_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InvalidArgument) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InvalidArgument) ProtoMessage() {}

func (x *InvalidArgument) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_errors_grpc_error_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InvalidArgument.ProtoReflect.Descriptor instead.
func (*InvalidArgument) Descriptor() ([]byte, []int) {
	return file_pkg_errors_grpc_error_proto_rawDescGZIP(), []int{0}
}

func (x *InvalidArgument) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InvalidArgument) GetDitales() []*Ditale {
	if x != nil {
		return x.Ditales
	}
	return nil
}

type BadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=Message,proto3" json:"Message,omitempty"`
	Ditales       []*Ditale              `protobuf:"bytes,10,rep,name=Ditales,proto3" json:"Ditales,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadRequest) Reset() {
	*x = BadRequest{}
	mi := &file_pkg_errors_grpc_error_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadRequest) ProtoMessage() {}

func (x *BadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_errors_grpc_error_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadRequest.ProtoReflect.Descriptor instead.
func (*BadRequest) Descriptor() ([]byte, []int) {
	return file_pkg_errors_grpc_error_proto_rawDescGZIP(), []int{1}
}

func (x *BadRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BadRequest) GetDitales() []*Ditale {
	if x != nil {
		return x.Ditales
	}
	return nil
}

type Ditale struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Desciption    string                 `protobuf:"bytes,1,opt,name=desciption,proto3" json:"desciption,omitempty"`
	Field         string                 `protobuf:"bytes,2,opt,name=field,proto3" json:"field,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ditale) Reset() {
	*x = Ditale{}
	mi := &file_pkg_errors_grpc_error_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ditale) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ditale) ProtoMessage() {}

func (x *Ditale) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_errors_grpc_error_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ditale.ProtoReflect.Descriptor instead.
func (*Ditale) Descriptor() ([]byte, []int) {
	return file_pkg_errors_grpc_error_proto_rawDescGZIP(), []int{2}
}

func (x *Ditale) GetDesciption() string {
	if x != nil {
		return x.Desciption
	}
	return ""
}

func (x *Ditale) GetField() string {
	if x != nil {
		return x.Field
	}
	return ""
}

func (x *Ditale) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_pkg_errors_grpc_error_proto protoreflect.FileDescriptor

const file_pkg_errors_grpc_error_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/errors/grpc/error.proto\x12\x05error\"T\n" +
	"\x0fInvalidArgument\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12'\n" +
	"\aDitales\x18\n" +
	" \x03(\v2\r.error.DitaleR\aDitales\"O\n" +
	"\n" +
	"BadRequest\x12\x18\n" +
	"\aMessage\x18\x01 \x01(\tR\aMessage\x12'\n" +
	"\aDitales\x18\n" +
	" \x03(\v2\r.error.DitaleR\aDitales\"T\n" +
	"\x06Ditale\x12\x1e\n" +
	"\n" +
	"desciption\x18\x01 \x01(\tR\n" +
	"desciption\x12\x14\n" +
	"\x05field\x18\x02 \x01(\tR\x05field\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05valueB9Z7github.com/alkosuv/grpc-playgroud/error/pkg/errors/grpcb\x06proto3"

var (
	file_pkg_errors_grpc_error_proto_rawDescOnce sync.Once
	file_pkg_errors_grpc_error_proto_rawDescData []byte
)

func file_pkg_errors_grpc_error_proto_rawDescGZIP() []byte {
	file_pkg_errors_grpc_error_proto_rawDescOnce.Do(func() {
		file_pkg_errors_grpc_error_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_errors_grpc_error_proto_rawDesc), len(file_pkg_errors_grpc_error_proto_rawDesc)))
	})
	return file_pkg_errors_grpc_error_proto_rawDescData
}

var file_pkg_errors_grpc_error_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_pkg_errors_grpc_error_proto_goTypes = []any{
	(*InvalidArgument)(nil), // 0: error.InvalidArgument
	(*BadRequest)(nil),      // 1: error.BadRequest
	(*Ditale)(nil),          // 2: error.Ditale
}
var file_pkg_errors_grpc_error_proto_depIdxs = []int32{
	2, // 0: error.InvalidArgument.Ditales:type_name -> error.Ditale
	2, // 1: error.BadRequest.Ditales:type_name -> error.Ditale
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_pkg_errors_grpc_error_proto_init() }
func file_pkg_errors_grpc_error_proto_init() {
	if File_pkg_errors_grpc_error_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_errors_grpc_error_proto_rawDesc), len(file_pkg_errors_grpc_error_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_errors_grpc_error_proto_goTypes,
		DependencyIndexes: file_pkg_errors_grpc_error_proto_depIdxs,
		MessageInfos:      file_pkg_errors_grpc_error_proto_msgTypes,
	}.Build()
	File_pkg_errors_grpc_error_proto = out.File
	file_pkg_errors_grpc_error_proto_goTypes = nil
	file_pkg_errors_grpc_error_proto_depIdxs = nil
}
