// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.35.1
// source: api/api.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ErrorTestService_GetError_FullMethodName = "/error.ErrorTestService/GetError"
)

// ErrorTestServiceClient is the client API for ErrorTestService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Описание gRPC-сервиса
type ErrorTestServiceClient interface {
	GetError(ctx context.Context, in *ErrorRequest, opts ...grpc.CallOption) (*ErrorResponse, error)
}

type errorTestServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewErrorTestServiceClient(cc grpc.ClientConnInterface) ErrorTestServiceClient {
	return &errorTestServiceClient{cc}
}

func (c *errorTestServiceClient) GetError(ctx context.Context, in *ErrorRequest, opts ...grpc.CallOption) (*ErrorResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ErrorResponse)
	err := c.cc.Invoke(ctx, ErrorTestService_GetError_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ErrorTestServiceServer is the server API for ErrorTestService service.
// All implementations must embed UnimplementedErrorTestServiceServer
// for forward compatibility.
//
// Описание gRPC-сервиса
type ErrorTestServiceServer interface {
	GetError(context.Context, *ErrorRequest) (*ErrorResponse, error)
	mustEmbedUnimplementedErrorTestServiceServer()
}

// UnimplementedErrorTestServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedErrorTestServiceServer struct{}

func (UnimplementedErrorTestServiceServer) GetError(context.Context, *ErrorRequest) (*ErrorResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetError not implemented")
}
func (UnimplementedErrorTestServiceServer) mustEmbedUnimplementedErrorTestServiceServer() {}
func (UnimplementedErrorTestServiceServer) testEmbeddedByValue()                          {}

// UnsafeErrorTestServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ErrorTestServiceServer will
// result in compilation errors.
type UnsafeErrorTestServiceServer interface {
	mustEmbedUnimplementedErrorTestServiceServer()
}

func RegisterErrorTestServiceServer(s grpc.ServiceRegistrar, srv ErrorTestServiceServer) {
	// If the following call panics, it indicates UnimplementedErrorTestServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ErrorTestService_ServiceDesc, srv)
}

func _ErrorTestService_GetError_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ErrorRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ErrorTestServiceServer).GetError(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ErrorTestService_GetError_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ErrorTestServiceServer).GetError(ctx, req.(*ErrorRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ErrorTestService_ServiceDesc is the grpc.ServiceDesc for ErrorTestService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ErrorTestService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "error.ErrorTestService",
	HandlerType: (*ErrorTestServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetError",
			Handler:    _ErrorTestService_GetError_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/api.proto",
}
